# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0005_auto_20181219_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
