# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0007_auto_20181219_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='submitted_by',
        ),
    ]
